/*

+-----------------------------------------------------------------+
|   Created by Chirag Mehta - http://chir.ag/tech/download/ntc    |
|-----------------------------------------------------------------|
|               ntc js (Name that Color JavaScript)               |
+-----------------------------------------------------------------+

All the functions, code, lists etc. have been written specifically
for the Name that Color JavaScript by Chirag Mehta unless otherwise
specified.

This script is released under the: Creative Commons License:
Attribution 2.5 http://creativecommons.org/licenses/by/2.5/

Sample Usage:

  <script type="text/javascript" src="ntc.js"></script>

  <script type="text/javascript">

    var n_match  = ntc.name("#6195ED");
    n_rgb = n_match[0]; // This is the RGB value of the closest matching color
    n_name = n_match[1]; // This is the text string for the name of the match
    n_shade_rgb = n_match[2]; // This is the RGB value for the name of colors shade
    n_shade_name = n_match[3]; // This is the text string for the name of colors shade
    n_exactmatch = n_match[4]; // True if exact color match, False if close-match

    alert(n_match);

  </script>

*/

var ntc = {

  init: function() {
    var color, rgb, hsl;

    for(var i = 0; i < ntc.names.length; i++)
    {
      color = "#" + ntc.names[i][0];
      rgb = ntc.rgb(color);
      hsl = ntc.hsl(color);
      ntc.names[i].push(rgb[0], rgb[1], rgb[2], hsl[0], hsl[1], hsl[2]);
    }
  },

  name: function(color) {
  
    if(this.names[0].length==3) {   // this gets called if the colours have been swapped, and we have
        this.init()                 // to regenerate the additional colour info
    }

    color = color.toUpperCase();
    if(color.length < 3 || color.length > 7)
      return ["#000000", "Invalid Color: " + color, "#000000", "", false];
    if(color.length % 3 == 0)
      color = "#" + color;
    if(color.length == 4)
      color = "#" + color.substr(1, 1) + color.substr(1, 1) + color.substr(2, 1) + color.substr(2, 1) + color.substr(3, 1) + color.substr(3, 1);

    var rgb = ntc.rgb(color);
    var r = rgb[0], g = rgb[1], b = rgb[2];
    var hsl = ntc.hsl(color);
    var h = hsl[0], s = hsl[1], l = hsl[2];
    var ndf1 = 0; ndf2 = 0; ndf = 0;
    var cl = -1, df = -1;

    for(var i = 0; i < ntc.names.length; i++)
    {
      if(color == "#" + ntc.names[i][0])
        return ["#" + ntc.names[i][0], ntc.names[i][1], ntc.shadergb(ntc.names[i][2]), ntc.names[i][2], true];

      ndf1 = Math.pow(r - ntc.names[i][3], 2) + Math.pow(g - ntc.names[i][4], 2) + Math.pow(b - ntc.names[i][5], 2);
      ndf2 = Math.abs(Math.pow(h - ntc.names[i][6], 2)) + Math.pow(s - ntc.names[i][7], 2) + Math.abs(Math.pow(l - ntc.names[i][8], 2));
      ndf = ndf1 + ndf2 * 2;
      if(df < 0 || df > ndf)
      {
        df = ndf;
        cl = i;
      }
    }

    return (cl < 0 ? ["#000000", "Invalid Color: " + color, "#000000", "", false] : ["#" + ntc.names[cl][0], ntc.names[cl][1], ntc.shadergb(ntc.names[cl][2]), ntc.names[cl][2], false]);
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  hsl: function (color) {

    var rgb = [parseInt('0x' + color.substring(1, 3)) / 255, parseInt('0x' + color.substring(3, 5)) / 255, parseInt('0x' + color.substring(5, 7)) / 255];
    var min, max, delta, h, s, l;
    var r = rgb[0], g = rgb[1], b = rgb[2];

    min = Math.min(r, Math.min(g, b));
    max = Math.max(r, Math.max(g, b));
    delta = max - min;
    l = (min + max) / 2;

    s = 0;
    if(l > 0 && l < 1)
      s = delta / (l < 0.5 ? (2 * l) : (2 - 2 * l));

    h = 0;
    if(delta > 0)
    {
      if (max == r && max != g) h += (g - b) / delta;
      if (max == g && max != b) h += (2 + (b - r) / delta);
      if (max == b && max != r) h += (4 + (r - g) / delta);
      h /= 6;
    }
    return [parseInt(h * 255), parseInt(s * 255), parseInt(l * 255)];
  },

  // adopted from: Farbtastic 1.2
  // http://acko.net/dev/farbtastic
  rgb: function(color) {
    return [parseInt('0x' + color.substring(1, 3)), parseInt('0x' + color.substring(3, 5)),  parseInt('0x' + color.substring(5, 7))];
  },
  
  shadergb: function (shadename) {
    for(var i = 0; i < ntc.shades.length; i++) {
      if(shadename == ntc.shades[i][1])
        return "#" + ntc.shades[i][0];
    }
    return "#000000";
  },
  
  
  saturation: [
    "Strong",
    "Medium",
    "Weak"
  ],
  
  luminance: [
    "Light",
    "Medium",
    "Dark"
  ],

  shade: [
"Red",
"Orange",
"Yellow",
"Green",
"Blue",
"Violet",
"Brown",
"Black",
"Grey",
"White"
],
  shades: [
 ["FF0000", "Red"],
["FFA500", "Orange"],
["FFFF00", "Yellow"],
["008000", "Green"],
["0000FF", "Blue"],
["ac35ce", "Violet"],
["623d0d", "Brown"],
["000000", "Black"],
["808080", "Grey"],
["FFFFFF", "White"]
],



  names: [
["7e1e9c", "purple", "Violet"],
["15b01a", "green", "Green"],
["0343df", "blue", "Blue"],
["ff81c0", "pink", "Violet"],
["653700", "brown", "Brown"],
["e50000", "red", "Red"],
["95d0fc", "light blue", "Blue"],
["029386", "teal", "Green"],
["f97306", "orange", "Orange"],
["96f97b", "light green", "Green"],
["c20078", "magenta", "Violet"],
["ffff14", "yellow", "Yellow"],
["75bbfd", "sky blue", "Blue"],
["929591", "grey", "Grey"],
["89fe05", "lime green", "Green"],
["bf77f6", "light purple", "Violet"],
["9a0eea", "violet", "Violet"],
["033500", "dark green", "Green"],
["06c2ac", "turquoise", "Green"],
["c79fef", "lavender", "Blue"],
["00035b", "dark blue", "Blue"],
["d1b26f", "tan", "Yellow"],
["00ffff", "cyan", "Blue"],
["13eac9", "aqua", "Blue"],
["06470c", "forest green", "Green"],
["ae7181", "mauve", "Red"],
["35063e", "dark purple", "Violet"],
["01ff07", "bright green", "Green"],
["650021", "maroon", "Red"],
["6e750e", "olive", "Brown"],
["ff796c", "salmon", "Orange"],
["e6daa6", "beige", "Yellow"],
["0504aa", "royal blue", "Blue"],
["001146", "navy blue", "Blue"],
["cea2fd", "lilac", "Violet"],
["000000", "black", "Black"],
["ff028d", "hot pink", "Red"],
["ad8150", "light brown", "Yellow"],
["c7fdb5", "pale green", "Green"],
["ffb07c", "peach", "Orange"],
["677a04", "olive green", "Green"],
["cb416b", "dark pink", "Red"],
["8e82fe", "periwinkle", "Blue"],
["53fca1", "sea green", "Green"],
["aaff32", "lime", "Green"],
["380282", "indigo", "Violet"],
["ceb301", "mustard", "Green"],
["ffd1df", "light pink", "Red"],
["cf6275", "rose", "Red"],
["0165fc", "bright blue", "Blue"],
["0cff0c", "neon green", "Green"],
["c04e01", "burnt orange", "Orange"],
["04d8b2", "aquamarine", "Green"],
["01153e", "navy", "Blue"],
["3f9b0b", "grass green", "Green"],
["d0fefe", "pale blue", "Blue"],
["840000", "dark red", "Brown"],
["be03fd", "bright purple", "Violet"],
["c0fb2d", "yellow green", "Green"],
["a2cffe", "baby blue", "Blue"],
["dbb40c", "gold", "Yellow"],
["8fff9f", "mint green", "Green"],
["580f41", "plum", "Violet"],
["4b006e", "royal purple", "Violet"],
["8f1402", "brick red", "Red"],
["014d4e", "dark teal", "Green"],
["610023", "burgundy", "Violet"],
["aaa662", "khaki", "Green"],
["137e6d", "blue green", "Green"],
["7af9ab", "seafoam green", "Green"],
["02ab2e", "kelly green", "Green"],
["9aae07", "puke green", "Green"],
["8eab12", "pea green", "Green"],
["b9a281", "taupe", "Yellow"],
["341c02", "dark brown", "Brown"],
["36013f", "deep purple", "Violet"],
["c1f80a", "chartreuse", "Green"],
["fe01b1", "bright pink", "Red"],
["fdaa48", "light orange", "Yellow"],
["9ffeb0", "mint", "Green"],
["b0ff9d", "pastel green", "Green"],
["e2ca76", "sand", "Green"],
["c65102", "dark orange", "Orange"],
["a9f971", "spring green", "Green"],
["a57e52", "puce", "Brown"],
["80f9ad", "seafoam", "Green"],
["6b8ba4", "grey blue", "Blue"],
["4b5d16", "army green", "Green"],
["363737", "dark grey", "Grey"],
["d5b60a", "dark yellow", "Green"],
["fac205", "goldenrod", "Yellow"],
["516572", "slate", "Blue"],
["90e4c1", "light teal", "Green"],
["a83c09", "rust", "Red"],
["040273", "deep blue", "Blue"],
["ffcfdc", "pale pink", "Red"],
["0485d1", "cerulean", "Blue"],
["ff474c", "light red", "Orange"],
["d2bd0a", "mustard yellow", "Green"],
["bf9005", "ochre", "Yellow"],
["ffff84", "pale yellow", "Yellow"],
["8c000f", "crimson", "Red"],
["ed0dd9", "fuchsia", "Red"],
["0b4008", "hunter green", "Green"],
["607c8e", "blue grey", "Blue"],
["5b7c99", "slate blue", "Blue"],
["b790d4", "pale purple", "Violet"],
["047495", "sea blue", "Blue"],
["d648d7", "pinkish purple", "Violet"],
["a5a502", "puke", "Green"],
["d8dcd6", "light grey", "Grey"],
["5ca904", "leaf green", "Green"],
["fffe7a", "light yellow", "Yellow"],
["380835", "eggplant", "Violet"],
["5a7d9a", "steel blue", "Blue"],
["658b38", "moss green", "Green"],
["98eff9", "robin's egg blue", "Blue"],
["ffffff", "white", "White"],
["789b73", "grey green", "Green"],
["87ae73", "sage", "Orange"],
["a03623", "brick", "Brown"],
["b04e0f", "burnt sienna", "Red"],
["7f2b0a", "reddish brown", "Brown"],
["ffffc2", "cream", "Yellow"],
["fc5a50", "coral", "Red"],
["03719c", "ocean blue", "Blue"],
["40a368", "greenish", "Green"],
["960056", "dark magenta", "Violet"],
["fd3c06", "red orange", "Orange"],
["703be7", "bluish purple", "Violet"],
["020035", "midnight blue", "Blue"],
["d6b4fc", "light violet", "Violet"],
["c0737a", "dusty rose", "Red"],
["2c6fbb", "medium blue", "Blue"],
["cdfd02", "greenish yellow", "Green"],
["b0dd16", "yellowish green", "Green"],
["601ef9", "purplish blue", "Violet"],
["5e819d", "greyish blue", "Blue"],
["6c3461", "grape", "Violet"],
["acbf69", "light olive", "Yellow"],
["5170d7", "cornflower blue", "Blue"],
["f10c45", "pinkish red", "Red"],
["ff000d", "bright red", "Red"],
["069af3", "azure", "Blue"],
["5729ce", "blue purple", "Violet"],
["045c5a", "dark turquoise", "Green"],
["0652ff", "electric blue", "Blue"],
["ffffe4", "off white", "Yellow"],
["b1d1fc", "powder blue", "Blue"],
["80013f", "wine", "Violet"],
["74a662", "dull green", "Green"],
["76cd26", "apple green", "Green"],
["7ef4cc", "light turquoise", "Blue"],
["bc13fe", "neon purple", "Violet"],
["1e488f", "cobalt", "Blue"],
["d46a7e", "pinkish", "Red"],
["6f7632", "olive drab", "Green"],
["0a888a", "dark cyan", "Green"],
["632de9", "purple blue", "Violet"],
["34013f", "dark violet", "Violet"],
["856798", "dark lavender", "Violet"],
["154406", "forrest green", "Green"],
["a2a415", "vomit", "Green"],
["ffa756", "pale orange", "Orange"],
["0b8b87", "greenish blue", "Green"],
["af884a", "dark tan", "Yellow"],
["06b48b", "green blue", "Green"],
["10a674", "bluish green", "Green"],
["a2bffe", "pastel blue", "Blue"],
["769958", "moss", "Green"],
["5cac2d", "grass", "Green"],
["cb0162", "deep pink", "Red"],
["980002", "blood red", "Red"],
["88b378", "sage green", "Orange"],
["02d8e9", "aqua blue", "Blue"],
["ca6641", "terracotta", "Orange"],
["caa0ff", "pastel purple", "Violet"],
["a9561e", "sienna", "Orange"],
["373e02", "dark olive", "Green"],
["c9ff27", "green yellow", "Green"],
["be0119", "scarlet", "Red"],
["82a67d", "greyish green", "Green"],
["3d1c02", "chocolate", "Brown"],
["5d06e9", "blue violet", "Violet"],
["6a79f7", "cornflower", "Blue"],
["ffb7ce", "baby pink", "Red"],
["343837", "charcoal", "Grey"],
["0a481e", "pine green", "Green"],
["e17701", "pumpkin", "Orange"],
["696112", "greenish brown", "Brown"],
["8b2e16", "red brown", "Brown"],
["6a6e09", "brownish green", "Green"],
["ff9408", "tangerine", "Orange"],
["fe7b7c", "salmon pink", "Red"],
["12e193", "aqua green", "Green"],
["b00149", "raspberry", "Violet"],
["887191", "greyish purple", "Violet"],
["f7879a", "rose pink", "Red"],
["fe019a", "neon pink", "Red"],
["030aa7", "cobalt blue", "Blue"],
["be6400", "orange brown", "Orange"],
["9a0200", "deep red", "Red"],
["fd411e", "orange red", "Orange"],
["cdc50a", "dirty yellow", "Green"],
["c875c4", "orchid", "Violet"],
["fe2c54", "reddish pink", "Red"],
["910951", "reddish purple", "Red"],
["fcb001", "yellow orange", "Yellow"],
["acfffc", "light cyan", "Blue"],
["82cafc", "sky", "Blue"],
["fa5ff7", "light magenta", "Red"],
["d9544d", "pale red", "Red"],
["01a049", "emerald", "Green"],
["ac9362", "dark beige", "Yellow"],
["7a9703", "ugly green", "Green"],
["1fa774", "jade", "Green"],
["96ae8d", "greenish grey", "Green"],
["c85a53", "dark salmon", "Red"],
["ce5dae", "purplish pink", "Violet"],
["05696b", "dark aqua", "Green"],
["cb7723", "brownish orange", "Brown"],
["a4be5c", "light olive green", "Green"],
["8cffdb", "light aqua", "Blue"],
["b66a50", "clay", "Orange"],
["39ad48", "medium green", "Green"],
["a0450e", "burnt umber", "Red"],
["49759c", "dull blue", "Blue"],
["b1916e", "pale brown", "Brown"],
["028f1e", "emerald green", "Green"],
["9c6d57", "brownish", "Brown"],
["735c12", "mud", "Brown"],
["b5485d", "dark rose", "Red"],
["9e3623", "brownish red", "Brown"],
["db4bda", "pink purple", "Red"],
["c94cbe", "pinky purple", "Violet"],
["526525", "camo green", "Green"],
["7bb274", "faded green", "Green"],
["d58a94", "dusty pink", "Red"],
["e03fd8", "purple pink", "Red"],
["89a203", "vomit green", "Green"],
["02590f", "deep green", "Green"],
["f8481c", "reddish orange", "Orange"],
["4a0100", "mahogany", "Brown"],
["3d0734", "aubergine", "Violet"],
["d5869d", "dull pink", "Red"],
["05472a", "evergreen", "Green"],
["448ee4", "dark sky blue", "Blue"],
["d1ffbd", "very light green", "White"],
["ffbacd", "pastel pink", "Red"],
["826d8c", "grey purple", "Violet"],
["d5ffff", "very light blue", "Blue"],
["874c62", "dark mauve", "Red"],
["4e7496", "cadet blue", "Blue"],
["d7fffe", "ice blue", "Blue"],
["fbeeac", "light tan", "Yellow"],
["667e2c", "dirty green", "Green"],
["04d9ff", "neon blue", "Blue"],
["7b0323", "wine red", "Red"],
["411900", "chocolate brown", "Brown"],
["84597e", "dull purple", "Violet"],
["b79400", "yellow brown", "Yellow"],
["3b638c", "denim", "Blue"],
["ffffd4", "eggshell", "White"],
["048243", "jungle green", "Green"],
["de7e5d", "dark peach", "Red"],
["7f5e00", "poop", "Green"],
["b26400", "umber", "Orange"],
["dfc5fe", "light lavender", "Violet"],
["fffd01", "bright yellow", "Yellow"],
["fec615", "golden yellow", "Yellow"],
["5a86ad", "dusty blue", "Blue"],
["21fc0d", "electric green", "Green"],
["75fd63", "lighter green", "Green"],
["59656d", "slate grey", "Grey"],
["25a36f", "teal green", "Green"],
["01386a", "marine blue", "Blue"],
["90b134", "avocado", "Green"],
["c9643b", "terra cotta", "Orange"],
["825f87", "dusty purple", "Violet"],
["a24857", "light maroon", "Red"],
["c44240", "reddish", "Orange"],
["9c6da5", "dark lilac", "Violet"],
["665fd1", "dark periwinkle", "Blue"],
["748b97", "bluish grey", "Grey"],
["c2be0e", "puke yellow", "Green"],
["94568c", "purplish", "Violet"],
["2000b1", "ultramarine", "Blue"],
["a00498", "barney purple", "Violet"],
["0b5509", "forest", "Green"],
["929901", "pea soup", "Green"],
["c9b003", "brownish yellow", "Green"],
["01f9c6", "bright teal", "Blue"],
["017a79", "bluegreen", "Green"],
["544e03", "green brown", "Green"],
["5539cc", "blurple", "Violet"],
["c6fcff", "light sky blue", "Blue"],
["8f99fb", "periwinkle blue", "Blue"],
["ceaefa", "pale violet", "Violet"],
["010fcc", "true blue", "Blue"],
["77926f", "green grey", "Green"],
["7f7053", "grey brown", "Green"],
["3c4d03", "dark olive green", "Green"],
["ffb16d", "apricot", "Orange"],
["916e99", "faded purple", "Violet"],
["de0c62", "cerise", "Red"],
["728639", "khaki green", "Green"],
["9f2305", "burnt red", "Red"],
["4f9153", "light forest green", "Green"],
["510ac9", "violet blue", "Violet"],
["eecffe", "pale lavender", "Violet"],
["8ffe09", "acid green", "Green"],
["866f85", "purple grey", "Violet"],
["fdff52", "lemon", "Yellow"],
["ff5b00", "bright orange", "Orange"],
["6fc276", "soft green", "Green"],
["f29e8e", "blush", "Red"],
["9b7a01", "yellowish brown", "Green"],
["08ff08", "fluorescent green", "Green"],
["aa23ff", "electric purple", "Violet"],
["738595", "steel", "Grey"],
["d8863b", "dull orange", "Yellow"],
["657432", "muddy green", "Green"],
["fcc006", "marigold", "Yellow"],
["017b92", "ocean", "Blue"],
["c292a1", "light mauve", "Red"],
["7b002c", "bordeaux", "Red"],
["7efbb3", "light blue green", "Blue"],
["faee66", "yellowish", "Yellow"],
["9dc100", "snot green", "Green"],
["b9ff66", "light lime green", "Green"],
["749551", "drab green", "Green"],
["658cbb", "faded blue", "Blue"],
["002d04", "dark forest green", "Green"],
["cb00f5", "hot purple", "Violet"],
["3c0008", "dark maroon", "Violet"],
["706c11", "brown green", "Brown"],
["748500", "swamp green", "Green"],
["6d5acf", "light indigo", "Blue"],
["5f34e7", "purpley blue", "Violet"],
["3d7afd", "lightish blue", "Blue"],
["01889f", "teal blue", "Blue"],
["3b5b92", "denim blue", "Blue"],
["7ebd01", "dark lime green", "Green"],
["eedc5b", "dull yellow", "Yellow"],
["c0fa8b", "pistachio", "Green"],
["fdff38", "lemon yellow", "Green"],
["9e0168", "red violet", "Violet"],
["cc7a8b", "dusky pink", "Red"],
["8a6e45", "dirt", "Brown"],
["062e03", "very dark green", "Green"],
["9e43a2", "medium purple", "Violet"],
["7f5f00", "poop", "Green"],
["a88905", "dark mustard", "Yellow"],
["94a617", "pea soup green", "Green"],
["fe83cc", "bubblegum pink", "Violet"],
["fe46a5", "barbie pink", "Red"],
["667c3e", "military green", "Green"],
["82cbb2", "pale teal", "Green"],
["a87900", "bronze", "Yellow"],
["fc2647", "pinky red", "Red"],
["bb3f3f", "dull red", "Red"],
["014182", "darkish blue", "Blue"],
["2976bb", "bluish", "Blue"],
["b59410", "dark gold", "Yellow"],
["bff128", "yellowy green", "Green"],
["2b5d34", "pine", "Green"],
["005249", "dark blue green", "Green"],
["ca7b80", "dirty pink", "Red"],
["658d6d", "slate green", "Green"],
["004577", "prussian blue", "Blue"],
["ad0afd", "bright violet", "Violet"],
["a55af4", "lighter purple", "Blue"],
["6f828a", "steel grey", "Blue"],
["a13905", "russet", "Red"],
["f4320c", "vermillion", "Red"],
["7a6a4f", "greyish brown", "Yellow"],
["820747", "red purple", "Violet"],
["fa2a55", "red pink", "Red"],
["0ffef9", "bright turquoise", "Blue"],
["b27a01", "golden brown", "Yellow"],
["056eee", "cerulean blue", "Blue"],
["6488ea", "soft blue", "Blue"],
["8cfd7e", "easter green", "Green"],
["feb308", "amber", "Yellow"],
["276ab3", "mid blue", "Blue"],
["7b5804", "poop brown", "Green"],
["9be5aa", "hospital green", "Green"],
["6140ef", "purpleish blue", "Blue"],
["661aee", "purply blue", "Violet"],
["c5c9c7", "silver", "Grey"],
["94b21c", "sickly green", "Green"],
["ff7855", "melon", "Orange"],
["ba6873", "dusky rose", "Red"],
["b96902", "brown orange", "Orange"],
["287c37", "darkish green", "Green"],
["9e003a", "cranberry", "Red"],
["98568d", "purpleish", "Violet"],
["feffca", "ecru", "White"],
["9d7651", "mocha", "Brown"],
["ff08e8", "bright magenta", "Violet"],
["a6814c", "coffee", "Yellow"],
["985e2b", "sepia", "Orange"],
["d3494e", "faded red", "Red"],
["fffe40", "canary yellow", "Green"],
["6241c7", "bluey purple", "Blue"],
["fffe71", "pastel yellow", "Yellow"],
["a5fbd5", "pale turquoise", "Blue"],
["c88d94", "greyish pink", "Red"],
["042e60", "marine", "Blue"],
["7a687f", "purplish grey", "Violet"],
["c69f59", "camel", "Yellow"],
["86775f", "brownish grey", "Yellow"],
["d5ab09", "burnt yellow", "Yellow"],
["f7022a", "cherry red", "Red"],
["b16002", "orangey brown", "Orange"],
["fdb0c0", "soft pink", "Red"],
["11875d", "dark sea green", "Green"],
["2ee8bb", "aqua marine", "Blue"],
["8af1fe", "robin egg blue", "Blue"],
["98f6b0", "light sea green", "Green"],
["60460f", "mud brown", "Brown"],
["c9ae74", "sandstone", "Yellow"],
["05480d", "british racing green", "Green"],
["de9dac", "faded pink", "Red"],
["f4d054", "maize", "Yellow"],
["c69c04", "ocre", "Yellow"],
["ffad01", "orange yellow", "Orange"],
["9b8f55", "dark khaki", "Brown"],
["aefd6c", "light lime", "Green"],
["26f7fd", "bright light blue", "Blue"],
["2baf6a", "jade green", "Green"],
["ac1db8", "barney", "Violet"],
["bd6c48", "adobe", "Orange"],
["0bf77d", "minty green", "Green"],
["2e5a88", "light navy blue", "Blue"],
["76a973", "dusty green", "Green"],
["000133", "very dark blue", "Blue"],
["3d9973", "ocean green", "Green"],
["a8b504", "mustard green", "Green"],
["7a5901", "poop brown", "Green"],
["645403", "olive brown", "Green"],
["f5054f", "pink red", "Red"],
["155084", "light navy", "Blue"],
["f6cefc", "very light purple", "Violet"],
["ffffcb", "ivory", "White"],
["c760ff", "bright lavender", "Violet"],
["0bf9ea", "bright aqua", "Blue"],
["6dedfd", "robin's egg", "Blue"],
["5fa052", "muted green", "Green"],
["7f5112", "medium brown", "Brown"],
["b66325", "copper", "Orange"],
["84b701", "dark lime", "Green"],
["fb2943", "strawberry", "Orange"],
["836539", "dirt brown", "Orange"],
["c1fd95", "celery", "Green"],
["02ccfe", "bright sky blue", "Blue"],
["885f01", "poo brown", "Green"],
["b17261", "pinkish brown", "Red"],
["befdb7", "celadon", "Green"],
["65fe08", "bright lime green", "Green"],
["9a3001", "auburn", "Red"],
["fe02a2", "shocking pink", "Red"],
["920a4e", "mulberry", "Red"],
["8ab8fe", "carolina blue", "Blue"],
["61e160", "lightish green", "Green"],
["edc8ff", "light lilac", "Violet"],
["b9cc81", "pale olive", "Green"],
["fb7d07", "pumpkin orange", "Orange"],
["cb9d06", "yellow ochre", "Yellow"],
["fe0002", "fire engine red", "Red"],
["0d75f8", "deep sky blue", "Blue"],
["fd4659", "watermelon", "Red"],
["044a05", "bottle green", "Green"],
["2a0134", "very dark purple", "Violet"],
["fbdd7e", "wheat", "Yellow"],
["6c7a0e", "murky green", "Brown"],
["76424e", "brownish purple", "Red"],
["5cb200", "kermit green", "Green"],
["0804f9", "primary blue", "Blue"],
["fa4224", "orangey red", "Orange"],
["e4cbff", "pale lilac", "Violet"],
["aa2704", "rust red", "Red"],
["c87606", "dirty orange", "Yellow"],
["c8aca9", "pinkish grey", "Red"],
["9d5783", "light plum", "Violet"],
["42b395", "greeny blue", "Green"],
["000435", "dark navy", "Blue"],
["ef1de7", "pink/purple", "Red"],
["019529", "irish green", "Green"],
["937c00", "baby poop", "Green"],
["99cc04", "slime green", "Green"],
["b0054b", "purplish red", "Red"],
["ab1239", "rouge", "Red"],
["ffc5cb", "light rose", "Red"],
["828344", "drab", "Green"],
["00022e", "dark navy blue", "Blue"],
["ccfd7f", "light yellow green", "Green"],
["c071fe", "easter purple", "Violet"],
["acbb0d", "snot", "Green"],
["fea993", "light salmon", "Red"],
["c83cb9", "purpley pink", "Violet"],
["8f7303", "poo", "Green"],
["990f4b", "berry", "Red"],
["7d7f7c", "medium grey", "Grey"],
["922b05", "brown red", "Red"],
["770001", "blood", "Brown"],
["a66fb5", "soft purple", "Violet"],
["c3909b", "grey pink", "Red"],
["2bb179", "bluey green", "Green"],
["03012d", "midnight", "Blue"],
["1f0954", "dark indigo", "Blue"],
["978a84", "warm grey", "Brown"],
["c4a661", "sandy brown", "Yellow"],
["cf0234", "cherry", "Red"],
["5a06ef", "blue/purple", "Violet"],
["536267", "gunmetal", "Blue"],
["490648", "deep violet", "Violet"],
["2a7e19", "tree green", "Green"],
["b25f03", "orangish brown", "Orange"],
["02c14d", "shamrock green", "Green"],
["f43605", "orangish red", "Orange"],
["c6f808", "greeny yellow", "Green"],
["d0c101", "ugly yellow", "Green"],
["436bad", "french blue", "Blue"],
["895b7b", "dusky purple", "Violet"],
["fffd74", "butter yellow", "Yellow"],
["fffeb6", "light beige", "Yellow"],
["f5bf03", "golden", "Yellow"],
["475f94", "dusky blue", "Blue"],
["7bc8f6", "lightblue", "Blue"],
["f075e6", "purply pink", "Violet"],
["6ba353", "off green", "Green"],
["bf9b0c", "ocher", "Yellow"],
["7f4e1e", "milk chocolate", "Brown"],
["ffd8b1", "light peach", "Brown"],
["a0025c", "deep magenta", "Violet"],
["af6f09", "caramel", "Yellow"],
["32bf84", "greenish teal", "Green"],
["befd73", "pale lime", "Green"],
["990147", "purple red", "Violet"],
["464196", "blueberry", "Violet"],
["77ab56", "asparagus", "Green"],
["fdfdfe", "pale grey", "Blue"],
["9dbcd4", "light grey blue", "Blue"],
["b1ff65", "pale lime green", "Green"],
["419c03", "grassy green", "Green"],
["638b27", "mossy green", "Green"],
["a2653e", "earth", "Orange"],
["dc4d01", "deep orange", "Orange"],
["b8ffeb", "pale aqua", "Blue"],
["be013c", "rose red", "Red"],
["ada587", "stone", "Green"],
["cd5909", "rusty orange", "Orange"],
["a4bf20", "pea", "Green"],
["9db92c", "sick green", "Green"],
["742802", "chestnut", "Brown"],
["0f9b8e", "blue/green", "Green"],
["9b5fc0", "amethyst", "Violet"],
["20c073", "dark mint green", "Green"],
["fdc1c5", "pale rose", "Red"],
["3b719f", "muted blue", "Blue"],
["cfaf7b", "fawn", "Yellow"],
["fef69e", "buff", "Yellow"],
["04f489", "turquoise green", "Green"],
["886806", "muddy brown", "Green"],
["3c9992", "sea", "Green"],
["ef4026", "tomato", "Red"],
["ff7fa7", "carnation pink", "Red"],
["ffff7e", "banana", "Yellow"],
["cfff04", "neon yellow", "Green"],
["a8a495", "greyish", "Green"],
["50a747", "mid green", "Green"],
["805b87", "muted purple", "Violet"],
["ff0490", "electric pink", "Red"],
["f1da7a", "sandy", "Yellow"],
["cd7584", "ugly pink", "Red"],
["06b1c4", "turquoise blue", "Blue"],
["a8415b", "light burgundy", "Red"],
["bccb7a", "greenish tan", "Green"],
["48c072", "dark mint", "Green"],
["b36ff6", "light urple", "Violet"],
["280137", "midnight purple", "Violet"],
["ff724c", "pinkish orange", "Orange"],
["cbf85f", "pear", "Green"],
["3f012c", "dark plum", "Violet"],
["24bca8", "tealish", "Green"],
["8f8ce7", "perrywinkle", "Violet"],
["ffab0f", "yellowish orange", "Orange"],
["ff964f", "pastel orange", "Orange"],
["6258c4", "iris", "Blue"],
["1805db", "ultramarine blue", "Blue"],
["35530a", "navy green", "Brown"],
["18d17b", "seaweed", "Green"],
["9cef43", "kiwi", "Green"],
["0aff02", "fluro green", "Green"],
["2dfe54", "bright light green", "Green"],
["2fef10", "vivid green", "Green"],
["58bc08", "frog green", "Green"],
["876e4b", "dull brown", "Green"],
["4e5481", "dusk", "Blue"],
["ac7e04", "mustard brown", "Yellow"],
["51b73b", "leafy green", "Green"],
["4984b8", "cool blue", "Blue"],
["070d0d", "almost black", "Green"],
["c8fd3d", "yellow/green", "Green"],
["d94ff5", "heliotrope", "Violet"],
["5edc1f", "green apple", "Green"],
["8f9805", "baby poop green", "Green"],
["6ecb3c", "apple", "Green"],
["df4ec8", "purpleish pink", "Red"],
["040348", "night blue", "Blue"],
["730039", "merlot", "Violet"],
["76ff7b", "lightgreen", "Green"],
["ec2d01", "tomato red", "Red"],
["aeff6e", "key lime", "Green"],
["b7fffa", "pale cyan", "Blue"],
["c7c10c", "vomit yellow", "Green"],
["6b4247", "purplish brown", "Red"],
["ff6cb5", "bubblegum", "Red"],
["01b44c", "shamrock", "Green"],
["ffa62b", "mango", "Orange"],
["d0fe1d", "lime yellow", "Green"],
["25ff29", "hot green", "Green"],
["5d1451", "grape purple", "Violet"],
["f0944d", "faded orange", "Orange"],
["87a922", "avocado green", "Green"],
["016795", "peacock blue", "Blue"],
["3ae57f", "weird green", "Green"],
["c95efb", "bright lilac", "Violet"],
["548d44", "fern green", "Green"],
["3f829d", "dirty blue", "Blue"],
["c45508", "rust orange", "Orange"],
["a484ac", "heather", "Violet"],
["00555a", "deep teal", "Green"],
["1fb57a", "dark seafoam", "Green"],
["ab9004", "baby poo", "Yellow"],
["bbf90f", "yellowgreen", "Green"],
["bcecac", "light sage", "Green"],
["7bfdc7", "light aquamarine", "Blue"],
["1ef876", "spearmint", "Green"],
["87fd05", "bright lime", "Green"],
["0add08", "vibrant green", "Green"],
["cffdbc", "very pale green", "Green"],
["feff7f", "faded yellow", "Yellow"],
["b5c306", "bile", "Green"],
["1e9167", "viridian", "Green"],
["fff4f2", "very light pink", "White"],
["947706", "puke brown", "Green"],
["f36196", "medium pink", "Red"],
["a442a0", "ugly purple", "Violet"],
["fffd37", "sunshine yellow", "Green"],
["35ad6b", "seaweed green", "Green"],
["c1c6fc", "light periwinkle", "Blue"],
["adf802", "lemon green", "Green"],
["696006", "greeny brown", "Green"],
["29465b", "dark grey blue", "Blue"],
["9cbb04", "bright olive", "Green"],
["75b84f", "turtle green", "Green"],
["bdf6fe", "pale sky blue", "Blue"],
["f7d560", "light mustard", "Yellow"],
["9f8303", "diarrhea", "Green"],
["017371", "dark aquamarine", "Green"],
["c27e79", "brownish pink", "Red"],
["889717", "baby poop green", "Green"],
["8756e4", "purpley", "Blue"],
["77a1b5", "greyblue", "Blue"],
["f504c9", "hot magenta", "Red"],
["758da3", "blue/grey", "Blue"],
["fff9d0", "pale", "Yellow"],
["33b864", "cool green", "Green"],
["fdee73", "sandy yellow", "Green"],
["c4fff7", "eggshell blue", "Blue"],
["94ac02", "barf green", "Green"],
["8cff9e", "baby green", "Green"],
["ad03de", "vibrant purple", "Violet"],
["8d8468", "brown grey", "Yellow"],
["0e87cc", "water blue", "Blue"],
["c0022f", "lipstick red", "Red"],
["fafe4b", "banana yellow", "Green"],
["a87dc2", "wisteria", "Violet"],
["673a3f", "purple brown", "Red"],
["b29705", "brown yellow", "Yellow"],
["d725de", "purple/pink", "Violet"],
["bffe28", "lemon lime", "Green"],
["647d8e", "grey/blue", "Blue"],
["b9484e", "dusty red", "Brown"],
["c74767", "deep rose", "Red"],
["3eaf76", "dark seafoam green", "Green"],
["bfac05", "muddy yellow", "Green"],
["fd798f", "carnation", "Red"],
["ae8b0c", "yellowy brown", "Yellow"],
["a50055", "violet red", "Violet"],
["0a437a", "twilight blue", "Blue"],
["0203e2", "pure blue", "Blue"],
["fe2f4a", "lightish red", "Red"],
["c14a09", "brick orange", "Red"],
["750851", "velvet", "Violet"],
["ffc512", "sunflower", "Yellow"],
["a6fbb2", "light mint green", "Green"],
["9af764", "light grass green", "Green"],
["8b88f8", "lavender blue", "Blue"],
["af2f0d", "rusty red", "Red"],
["a552e6", "lightish purple", "Violet"],
["4b0101", "dried blood", "Brown"],
["b7c9e2", "light blue grey", "Blue"],
["71aa34", "leaf", "Green"],
["fc824a", "orangish", "Orange"],
["b1d27b", "pale olive green", "Green"],
["f1f33f", "off yellow", "Green"],
["f0833a", "dusty orange", "Orange"],
["ffff81", "butter", "Yellow"],
["0c1793", "royal", "Blue"],
["005f6a", "petrol", "Green"],
["2afeb7", "greenish cyan", "Green"],
["c3fbf4", "duck egg blue", "Blue"],
["ff69af", "bubble gum pink", "Red"],
["85a3b2", "bluegrey", "Blue"],
["964e02", "warm brown", "Green"],
["4e518b", "twilight", "Violet"],
["feb209", "saffron", "Yellow"],
["5d21d0", "purple/blue", "Violet"],
["a88f59", "dark sand", "Yellow"],
["0339f8", "vibrant blue", "Blue"],
["beae8a", "putty", "Yellow"],
["4da409", "lawn green", "Green"],
["4b6113", "camouflage green", "Green"],
["fe828c", "blush pink", "Red"],
["6e1005", "reddy brown", "Brown"],
["a90308", "darkish red", "Red"],
["21c36f", "algae green", "Green"],
["cf524e", "dark coral", "Red"],
["41fdfe", "bright cyan", "Blue"],
["ddd618", "piss yellow", "Yellow"],
["db5856", "pastel red", "Red"],
["00fbb0", "greenish turquoise", "Green"],
["1b2431", "dark", "Blue"],
["ca0147", "ruby", "Red"],
["6f7c00", "poop green", "Green"],
["fe420f", "orangered", "Orange"],
["fedf08", "dandelion", "Yellow"],
["680018", "claret", "Red"],
["fed0fc", "pale mauve", "Red"],
["d5174e", "lipstick", "Red"],
["fe86a4", "rosa", "Red"],
["030764", "darkblue", "Blue"],
["ab7e4c", "tan brown", "Yellow"],
["758000", "poop green", "Green"],
["8c0034", "red wine", "Red"],
["fc86aa", "pinky", "Red"],
["606602", "mud green", "Green"],
["63f7b4", "light greenish blue", "Blue"],
["5f9e8f", "dull teal", "Blue"],
["8d5eb7", "deep lavender", "Violet"],
["152eff", "vivid blue", "Blue"],
["a75e09", "raw umber", "Red"],
["b6ffbb", "light mint", "Green"],
["cafffb", "light light blue", "Blue"],
["1bfc06", "highlighter green", "Green"],
["7ea07a", "greeny grey", "Green"],
["89a0b0", "bluey grey", "Blue"],
["54ac68", "algae", "Green"],
["5c8b15", "sap green", "Green"],
["ffb19a", "pale salmon", "Red"],
["4f738e", "metallic blue", "Blue"],
["d6fffa", "ice", "Blue"],
["a0bf16", "gross green", "Green"],
["3e82fc", "dodger blue", "Blue"],
["fb5581", "warm pink", "Red"],
["56fca2", "light green blue", "Green"],
["699d4c", "flat green", "Green"],
["1f3b4d", "dark blue grey", "Blue"],
["b2713d", "clay brown", "Orange"],
["fce166", "sand yellow", "Yellow"],
["fd5956", "grapefruit", "Red"],
["fe4b03", "blood orange", "Red"],
["d6fffe", "very pale blue", "Blue"],
["c77986", "old pink", "Red"],
["ff073a", "neon red", "Red"],
["f9bc08", "golden rod", "Yellow"],
["4e0550", "plum purple", "Violet"],
["ffe5ad", "pale peach", "Brown"],
["728f02", "dark yellow green", "Green"],
["9d0216", "carmine", "Red"],
["015482", "deep sea blue", "Green"],
["d90166", "dark hot pink", "Red"],
["4b57db", "warm blue", "Blue"],
["e6f2a2", "light khaki", "Green"],
["8fae22", "icky green", "Green"],
["23c48b", "greenblue", "Green"],
["734a65", "dirty purple", "Violet"],
["021bf9", "rich blue", "Blue"],
["ba9e88", "mushroom", "Yellow"],
["3c73a8", "flat blue", "Blue"],
["214761", "dark slate blue", "Blue"],
["598556", "dark sage", "Green"],
["ff6163", "coral pink", "Orange"],
["089404", "true green", "Green"],
["751973", "darkish purple", "Violet"],
["7f684e", "dark taupe", "Green"],
["95a3a6", "cool grey", "Blue"],
["fdff63", "canary", "Yellow"],
["96b403", "booger green", "Green"],
["d1768f", "muted pink", "Red"],
["8e7618", "hazel", "Brown"],
["02066f", "dark royal blue", "Blue"],
["9900fa", "vivid purple", "Violet"],
["014600", "racing green", "Green"],
["ac7434", "leather", "Orange"],
["01c08d", "green/blue", "Green"],
["ffda03", "sunflower yellow", "Yellow"],
["720058", "rich purple", "Violet"],
["d767ad", "pale magenta", "Red"],
["c2ff89", "light yellowish green", "Green"],
["3a18b1", "indigo blue", "Blue"],
["9d0759", "dark fuchsia", "Red"],
["ffe36e", "yellow tan", "Yellow"],
["20f986", "wintergreen", "Green"],
["fb5ffc", "violet pink", "Violet"],
["13bbaf", "topaz", "Green"],
["78d1b6", "seafoam blue", "Green"],
["fddc5c", "light gold", "Yellow"],
["86a17d", "grey/green", "Green"],
["90fda9", "foam green", "Green"],
["ffffb6", "creme", "Yellow"],
["247afd", "clear blue", "Blue"],
["31668a", "ugly blue", "Blue"],
["cb6843", "terracota", "Orange"],
["1d0200", "very dark brown", "Violet"],
["fcf679", "straw", "Green"],
["fefcaf", "parchment", "Yellow"],
["fdb915", "orangey yellow", "Orange"],
["719f91", "greyish teal", "Green"],
["2138ab", "sapphire", "Blue"],
["107ab0", "nice blue", "Blue"],
["ca6b02", "browny orange", "Orange"],
["bcf5a6", "washed out green", "Green"],
["7bf2da", "tiffany blue", "Blue"],
["a0febf", "light seafoam", "Green"],
["4efd54", "light neon green", "Green"],
["53fe5c", "light bright green", "Green"],
["76fda8", "light bluish green", "Blue"],
["f6688e", "rosy pink", "Red"],
["ff9a8a", "peachy pink", "Red"],
["b1fc99", "pale light green", "Green"],
["c87f89", "old rose", "Red"],
["63a950", "fern", "Green"],
["26538d", "dusk blue", "Blue"],
["7f8f4e", "camo", "Green"],
["b75203", "burnt siena", "Orange"],
["0cdc73", "tealish green", "Green"],
["698339", "swamp", "Green"],
["cba560", "sand brown", "Yellow"],
["8b3103", "rust brown", "Red"],
["fd8d49", "orangeish", "Orange"],
["3a2efe", "light royal blue", "Violet"],
["875f42", "cocoa", "Brown"],
["ca9bf7", "baby purple", "Violet"],
["9a6200", "raw sienna", "Green"],
["2cfa1f", "radioactive green", "Green"],
["c4fe82", "light pea green", "Green"],
["ac4f06", "cinnamon", "Red"],
["f2ab15", "squash", "Yellow"],
["3c4142", "charcoal grey", "Blue"],
["9dff00", "bright yellow green", "Green"],
["b6c406", "baby puke green", "Green"],
["40fd14", "poison green", "Green"],
["efc0fe", "light lavendar", "Violet"],
["850e04", "indian red", "Red"],
["fff39a", "dark cream", "Yellow"],
["c7ac7d", "toupe", "Yellow"],
["fdb147", "butterscotch", "Yellow"],
["6832e3", "burple", "Violet"],
["a9be70", "tan green", "Orange"],
["ffdf22", "sun yellow", "Green"],
["fdde6c", "pale gold", "Yellow"],
["c8ffb0", "light light green", "Green"],
["8fb67b", "lichen", "Orange"],
["b5ce08", "green/yellow", "Green"],
["054907", "darkgreen", "Green"],
["1d5dec", "azul", "Blue"],
["fff917", "sunny yellow", "Yellow"],
["d0e429", "sickly yellow", "Yellow"],
["009337", "kelley green", "Green"],
["7e4071", "bruise", "Violet"],
["6f6c0a", "browny green", "Brown"],
["6b7c85", "battleship grey", "Blue"],
["5684ae", "off blue", "Blue"],
["fffa86", "manilla", "Yellow"],
["c9d179", "greenish beige", "Green"],
["410200", "deep brown", "Brown"],
["da467d", "darkish pink", "Red"],
["fffd78", "custard", "Yellow"],
["7d7103", "ugly brown", "Green"],
["507b9c", "stormy blue", "Blue"],
["c48efd", "liliac", "Violet"],
["ad900d", "baby poop brown", "Yellow"],
["997570", "reddish grey", "Brown"],
["ffb2d0", "powder pink", "Red"],
["430541", "eggplant purple", "Violet"],
["fffcc4", "egg shell", "Yellow"],
["d3b683", "very light brown", "Brown"],
["bdf8a3", "tea green", "Green"],
["ff6f52", "orange pink", "Orange"],
["b7e1a1", "light grey green", "Green"],
["8ee53f", "kiwi green", "Green"],
["63b365", "boring green", "Green"],
["b2fba5", "light pastel green", "Green"],
["ff63e9", "candy pink", "Red"],
["983fb2", "purply", "Violet"],
["947e94", "purpley grey", "Violet"],
["ac86a8", "dusty lavender", "Violet"],
["ccad60", "desert", "Yellow"],
["966ebd", "deep lilac", "Violet"],
["e78ea5", "pig pink", "Red"],
["c2b709", "olive yellow", "Green"],
["a7ffb5", "light seafoam green", "Green"],
["a6c875", "light moss green", "Green"],
["dd85d7", "lavender pink", "Violet"],
["08787f", "deep aqua", "Green"],
["afa88b", "bland", "Green"],
["ff0789", "strong pink", "Red"],
["0cb577", "green teal", "Green"],
["017374", "deep turquoise", "Green"],
["1f6357", "dark green blue", "Green"],
["05ffa6", "bright sea green", "Green"],
["9bb53c", "booger", "Green"],
["533cc6", "blue with a hint of purple", "Blue"],
["2242c7", "blue blue", "Blue"],
["3778bf", "windows blue", "Blue"],
["61de2a", "toxic green", "Green"],
["0c06f7", "strong blue", "Blue"],
["0a5f38", "spruce", "Green"],
["d99b82", "pinkish tan", "Red"],
["efb435", "macaroni and cheese", "Yellow"],
["5e9b8a", "grey teal", "Green"],
["4c9085", "dusty teal", "Green"],
["388004", "dark grass green", "Green"],
["a5a391", "cement", "Green"],
["fcfc81", "yellowish tan", "Green"],
["952e8f", "warm purple", "Violet"],
["65ab7c", "tea", "Green"],
["d4ffff", "really light blue", "Blue"],
["70b23f", "nasty green", "Green"],
["894585", "light eggplant", "Red"],
["69d84f", "fresh green", "Green"],
["a8ff04", "electric lime", "Green"],
["b2996e", "dust", "Grey"],
["56ae57", "dark pastel green", "Green"],
["acc2d9", "cloudy blue", "Blue"]
]

}

ntc.init();